# Generated by Django 2.0.1 on 2018-01-16 20:57

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('is_active', models.BooleanField(default=True, verbose_name='계정 활성화 여부')),
                ('is_staff', models.BooleanField(default=True, verbose_name='관리자 여부')),
                ('is_superuser', models.BooleanField(default=True, verbose_name='최고 관리자 여부')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인')),
                ('last_change_password_date', models.DateTimeField(null=True, verbose_name='마지막 패스워드 변경일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '관리자 계정',
                'verbose_name_plural': '관리자 계정 리스트',
                'db_table': 'tb_staff',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('is_active', models.BooleanField(default=True, verbose_name='계정 활성화 여부')),
                ('last_change_password_date', models.DateTimeField(null=True, verbose_name='마지막 패스워드 변경일')),
            ],
            options={
                'verbose_name': '사용자 계정',
                'verbose_name_plural': '사용자 계정 리스트',
                'db_table': 'tb_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
