# Generated by Django 2.1.7 on 2019-03-28 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModifiedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('order', models.BigIntegerField(db_index=True, null=True, verbose_name='히스토리 순서')),
            ],
            options={
                'verbose_name': '사용자 정보 변경 내역',
                'verbose_name_plural': '사용자 정보 변경 내역 리스트',
                'db_table': 'user_modified_history',
            },
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(null=True, verbose_name='birth_date'),
        ),
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(max_length=128, null=True, verbose_name='device_id'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=256, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verify_date',
            field=models.DateTimeField(null=True, verbose_name='email_verify_date'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')], null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='ip',
            field=models.CharField(max_length=16, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(null=True, verbose_name='reg_date'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'NORMAL'), (1, 'ABUSER'), (2, 'DORMANT'), (3, 'SECEDER'), (4, 'NEED_ACTIVATION')], null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='u_id'),
        ),
        migrations.AddField(
            model_name='usermodifiedhistory',
            name='u_idx',
            field=models.ForeignKey(db_column='idx', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='u_idx'),
        ),
        migrations.AlterIndexTogether(
            name='usermodifiedhistory',
            index_together={('id', 'order')},
        ),
    ]
