# Generated by Django 2.0.2 on 2018-05-03 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account_app', '0002_auto_20180328_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
