# Generated by Django 2.1.7 on 2019-03-29 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_auto_20190328_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodifiedhistory',
            name='u_idx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='u_idx'),
        ),
    ]
