# Generated by Django 2.0.2 on 2018-02-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_auto_20180220_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(editable=False, max_length=16, unique=True, verbose_name='u_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idx',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='u_idx'),
        ),
    ]
