# Generated by Django 2.0.2 on 2018-05-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_auto_20180503_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='u_id'),
        ),
    ]
