# Generated by Django 2.1.7 on 2019-03-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_auto_20180504_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(null=True, verbose_name='birth_date'),
        ),
        migrations.AddField(
            model_name='user',
            name='device_id',
            field=models.CharField(max_length=128, null=True, verbose_name='device_id'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=256, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verify_date',
            field=models.DateTimeField(null=True, verbose_name='email_verify_date'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')], null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='ip',
            field=models.CharField(max_length=16, null=True, verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(null=True, verbose_name='reg_date'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'NORMAL'), (1, 'ABUSER'), (2, 'DORMANT'), (3, 'SECEDER'), (4, 'NEED_ACTIVATION')], null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
