# Generated by Django 2.1.7 on 2019-04-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account_app', '0004_auto_20190329_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodifiedhistory',
            old_name='u_idx',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verify_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(null=True, verbose_name='생일'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_date',
            field=models.DateTimeField(null=True, verbose_name='이메일 인증 날짜'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='인증여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')], null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_date',
            field=models.DateTimeField(null=True, verbose_name='가입일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'NORMAL'), (1, 'ABUSER'), (2, 'DORMANT'), (3, 'SECEDER'), (4, 'NEED_ACTIVATION')],
                                      null=True, verbose_name='계정 상태'),
        ),
    ]
