# Generated by Django 2.1.7 on 2019-03-28 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account_app', '0005_usermodifiedhistory'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='usermodifiedhistory',
            index_together={('id', 'order')},
        ),
    ]
