image: ridibooks/python:gitlab-ci-2018.11.12.1

stages:
- test

test:
  stage: test
  before_script:
  - export TAG=${CI_COMMIT_SHA::8}
  script:
  - make pm-test-up
  - docker exec account-www-123456 ls
  - docker exec account-www-123456 ls docs
  - docker exec account-www-123456 ls src
  - make pm-test-run
  after_script:
  - make pm-test-down