image: ridibooks/python:gitlab-ci-2018.11.12.1

stages:
- build
- test

build:
  stage: build
  before_script:
  - export TAG=${CI_COMMIT_SHA::8}
  script:
  - docker-compose -f ./docs/postman/pm-build.yml build

test:
  image: ridibooks/python:bootstrap-django-2018.11.12.2
  stage: test
  before_script:
  - make pm-test