image: ridibooks/python:bootstrap-django-2018.11.12.2

stages:
- build
- test

build:
  image: ridibooks/python:gitlab-ci-2018.11.12.1
  stage: build
  before_script:
  - export TAG=${CI_COMMIT_SHA::8}
  script:
  - docker-compose -f ./docs/postman/build.yml build

test:
  image: ridibooks/pm-test:latest
  variables:
    PM_API_KEY: $PM_API_KEY
    COLLECTION_NAMES: "['Account']"
    ENVIRONMENT: development
    STATUS_CHECK_URL: https://account.dev.ridi.io/health
  before_script:
  - export TAG=${CI_COMMIT_SHA::8}
  - echo "127.0.0.1 account.dev.ridi.io" >> /etc/hosts
  - docker-compose up
  script:
  - bash ./docs/postman/pm-test.sh
