image: ridibooks/python:gitlab-ci-2018.11.12.1

stages:
- test

test:
  stage: test
  script:
  - export TAG=${CI_COMMIT_SHA::8}
  - docker exec account-www-123456 find ./  -maxdepth 2
  - docker ps
#  - make pm-test-run
  after_script:
  - make pm-test-down