image: ridibooks/python:bootstrap-django-2018.11.12.2

stages:
- build
- test

build:
  image: ridibooks/python:gitlab-ci-2018.11.12.1
  stage: build
  variables:
    CI_DEBUG_TRACE: "true"
  before_script:
  - "echo $PM_API_KEY"
  - echo $PM_API_KEY
  - echo ${PM_API_KEY}
  - export TAG=${CI_COMMIT_SHA::8}
  - export PM_API_KEY=${PM_API_KEY}
  - echo ${PM_API_KEY}
  script:
  - "echo $PM_API_KEY"
  - echo $PM_API_KEY
  - echo "$PM_API_KEY"
  - docker-compose -f ./docs/postman/build.yml build

test:
  image: ridibooks/python:gitlab-ci-2018.11.12.1
  before_script:
  - export TAG=${CI_COMMIT_SHA::8}
  - export PM_API_KEY=${PM_API_KEY}
#  - echo "127.0.0.1 account.dev.ridi.io" >> /etc/hosts
#  - docker-compose -f ./docs/postman/docker-compose.yml up
  script:
  - "docker run -e PM_API_KEY=$PM_API_KEY --env-file ./docs/postman/.env ridibooks/pm-test:feature_image /bin/bash pm-test.sh"
  after_script:
  - docker-compose down
