image: ridibooks/python:bootstrap-django-2018.11.12.2

stages:
- build
- test

before_script:
- export TAG=${CI_COMMIT_SHA::8}

build:
  image: ridibooks/python:gitlab-ci-2018.11.12.1
  stage: build
  script:
  - docker-compose -f ./docs/postman/build.yml build

test:
  image: ridibooks/pm-test:feature_image
  services:
  - name: pm-test/account-mariadb:${TAG}
    alias: account-mariadb
  - name: redis:4.0.6
    alias: account-redis
  - name: pm-test/account-www:${TAG}
    alias: account-www
  - name: pm-test/account-nginx:${TAG}
    alias: account.dev.ridi.io
  variables:
    PM_API_KEY: $PM_API_KEY
    COLLECTION_NAMES: "['Account']"
    ENVIRONMENT: development
    STATUS_CHECK_URL: https://account.dev.ridi.io/health
  before_script:
  - echo "127.0.0.1 account.dev.ridi.io" >> /etc/hosts
  script:
  - bash pm-test.sh
