image: ridibooks/python:gitlab-ci-2018.11.12.1

stages:
- test

test:
  stage: test
  script:
  - make pm-test-up
  - docker exec account-www-123456 ls
  - docker exec account-www-123456 ls docs
  after_script:
  - make pm-test-down