sudo: required
language: python
python:
- '3.6'

services:
- docker

env:
  global:
  - secure: 2NLIzqg5hCGw5J8yPLDGB0u1nfmGBN0WSkg1cnkniaUblHZ1TFs86Ou69dk86l75Yoof/nlUju3vEFBnXoBUVQIyHMh0WwyKnglY2w55wRlVDcBDDFnVAg8d0aOezGs3ghUx+4TYnTRxNzSc32AEBbodlkUYeXiUEgQyr/63DhO8LrheDjtWALSDmtM4FQkWL6llo0E5NON6So5BxZBeY04dh+mwvX5+OBC6En1+6f6dCgjWKGJVTk0QOxA9I/OlgfOm/FNQi9fzKkYQlathSgPipzAlLFJ+a8/r9DRZaHd5i2HEWRmkLVJebS1ot2ly5yQ2K+jy9drVC3kEjE/jDvsx0WhcxSRqaw36PIeMpQIj9gxFNNMRHDV96rh/uE4shsjVhHbjs31RRjwFCMtW87WlHF9vp4u1d3N2H7PaXj1rxaQWGMAhld0+dHsw0a2LERSBrFCL5X3Nh28LdypBwzHYm6QZ0/fpxWGjywVpBdBfzP+V05qLyYSPOvoxlNN0F4c0h3IP7Mk7/NqnXFjrYh3b2wq2H4UtRQHMECn2SDh3WNFyvPxb64U5EXzMki0cMtjbsVEWKFLnfCdkFCeTZXSmAVGp/SKtu2dl5EjrQ7yvE9e2b7Nh9LE8qVjHObbSnzv3AjsHj6PN9oF4PixxvcvPZMZuCt6lLF6GNfraYHA=
  - secure: pVszyLSErkktF8G8fP4LeExPFcm/AliuzTH0jQlIvNTE3ImOgElCxXQW8IRmYpgzSPtNqRiHkhzl1MD7Q55WZXm2eQfITEEpWsHpu+y3K95qH4SXXBnvYEcx0SkT5n7hZ6DIXn0YseY9J4WogX0jh1Vv6/Wy+8y68PY625/8TNLl5I/GI/AIVIakxQ4QY6nIkXiY8rLkvf7PyVQpUMDu2QHUsKa7CB6O+y2JDol3WF4zEtiEWsFAxkE00dvTe98NEgUvtDUMGAsyYbFIHA3kl0W4o9exMw75xPXLGfzx06rY9dYO66+4JHpygRQnBqBopxeJgR2E3k2s37e+8wUNk6T+MxcYrR93Qd0L/ziGYDoJ6Cowz6p11YPHflSRBdt6xJwag8ndBM06o7HMdjAtsbIjgHHdcorCk7CjtGAgQhR4QAO3l60bGGzCt7L51RGIwxvvScJBcqXGqelEw0/GoU0OKiC4Xhb+JKr1ncc7eRUvU/d1nRFUcOvvxeBiqBsi/esWLptmn0dsdrlLiMpFadc3Hw9S6qdOj2E94kT8+nBsVtueP4iku2AybVaPUj7iVFGmG8g7o5zD47wS2rqCj8sGBjPE9jbjpckYzJJBCXxPiepMOr1nOBjvI4ewQcOiI/LgWjqHVWNTuilAvJ0169/gH8x89FS8avbowStwwLY=
  - secure: nrZG66Hhmm7aH2OimyxlaQfIvJR6IkNR76S+zhov6o3kNpnnw4PGtr78whTXBuveeO5QAN/S3qA4yQUryQk0Or6xg3fShDJSVTwTdc92eRRd8kEV72vkP9Iy5p/GwmwB6yEb0JdCH7G+0IO5IDAOEyPnJNUFVgmxB+updiE9YlemAILVCTUKQmbuxwrmrcCuW9T5g1VOF8OOLz3fxqIdZrv2kv5q2CzEy+0KKDGKequDWvQRK2ejrdf8EEJwmZHDhjXITnOQFnduqfnwkU+lbX+1K8PH4ysRb6UxMsADp0NKeymC+aUchrg0qeD+1vIYAxwJS6Dns3EjwHfiktAJ44v1QwhF3GAbiKFkvso0SzZu8JqIHD26Ct+9+pBERPE679+9kp57i3zrTUCfe7cWYNFAyMYs+w1FNMPBMeZlywyGREnxy7l3LcNMk+QrbxdJrqVV1Pbu67BqmjoWZLfhU+JBBeG1qVlhohcU1sHq85C+HzVy6L6F6u0XN01YUwZpJc6ywxpU9BpibActGI2ILzxW4MRkCIGye4IOnkZAjKM8rAKOgZPITbPax3ogt1FAIFAFXkK33fARAZMUeN9/kIR184mx4/WUSv0PuqiA218ns6/ih/igADful2B7Mal2wyVAjYl4a9BASUsNlO3pmOxeCHUEWX8cjccXBw83Bdw=
  - secure: m60wLQKswtwoB31n21Zcqg0+VTICfSnjowLeB4B5Dwi+Fnx4qYPzyvl0Elus1EDGSMRij/UHVS4PjfwXyXpqdfBGC5RjLJFgbEuCCZFNeKGNbJf5tY4zFJXpeReT8cAATnsdAHxMsWb0WowYq8UDPX58jQehcoqRPnv2gzUcm0EHLGrPe/W4vpS0B8BlFiEnxkgCikQgOK5wbVWF6HsEYwYs9IK3KPiIIy2IL/tJOUJ/PnDtWpxAcdmLjkHlFL7sDJFldNkgVq75i7PL4cPLs7NMBNGbwn7gMffmrr8gt/hZIGGvyuAM50iji2TjzqngF8DofxGY0xmA34/z5Ak7lw9EIiNqOZxGCz5M46OjlNdxgIBS4wOL81HiMvcQD9RRDkmxwdrEjDVRgTENejMtGgDeoLf3FMCXQ7DIPZBmbRWJj49ff8Z6lEzmXTcDuz2DDznR0Ij4o8i/A8obndWofUQCY+ZgKjG7J6l/66Q4Sn8P3NkSfQpcI0TOmWJ3wc/mbBBoQSMn1ViECXbcsFJi7tPuPrrJi/457o9U0MiQmNdYkh8Lv/e2MrVdVqFTnYLeqQ1hAq8rxYMoPQMjlGZCQ+k2yuR6WqOx7hbhch9dr9l+P+KDlsqQzipu6O19K57Vai+Zf/K0v5Ld1/mWy0xZBSXBR4pW2aRxe5XDzNH7yGM=
  - secure: hViLtrWbEPLPg8UnvKKwXOxCv2SwYe9ElRowGPOvYfkbKPP6yTbqRnFqg13OPAN4jTB6lH0Ukg+lvz3MBSu8fxO7ye3iwyp5804Uhr5ho/loIBIfTs/TsfxxaCN8+OIfAHeRb5inOPCvoBwtp9IZ1u5N3sYfqCLbLo1cyABlPy02KsAnv6IHZ9wsGn/wHgU5hV3eAjRAhZlHzSsYxbKgxjJX/oEDA+PEqfoo/pXzef6tFAJbahORz/cpvg76yPXz1z5DL4Vmc+/AMzPzJTT5UaVsrmptHv/6QcMR2tbUGh1/ztRujp6IJZ1f+YlSLkzbB639k55ZzLjpzmUkzug2lefxopOpgreITucYXZgDlamumvXubeu+0K99m0tro9okWJ40DWd7vQxxhiWihChgsUloV9f0cl3FEcESTUyCRd1JBA563Xhd3z0x7xwpCm2CvekgdkyTjR0ekLEj0c9+C1w1mDPcKCZkUEdssFFhV3yej7Wm2Jh1ptmi64xWxwDTMUaiHt5IAdA2bK21jsZBgSVh5ImCqjlZSinhwMBig8sO4IhpyJSaEyXU3RboyYwkUJcKrTRXxPlFmyRsodVyycoGm/q6vNXmGTSBXEH5/51GUbXDpJKFYMyaeaba57iHm9+Ckd4DPavrapjy7BRov8oBZwb+Ts9G2TyOLKPFG/A=
  matrix:
  - ENVIRONMENT=development ACCOUNT_ECR=$DEV_ACCOUNT_ECR AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY

before_script:
- pip3 install -r docs/requirements/development.txt
- make settings
- sudo service mysql stop
- make pre-test

script:
- make lint
- make test
- make check-deprecated

before_deploy:
- pip3 install awscli
- pip3 install ecs-deploy
- bash docs/travis/pre_build.sh
- bash docs/travis/build/account.sh
- bash docs/travis/push/account.sh

deploy:
  provider: script
  script: bash docs/travis/deploy.sh
  on:
    branch: release

after_deploy:
- bash docs/travis/after_deploy.sh
