
sudo: required

language: python
python:
  - "3.6"

branches:
only:
  - master
  - /^release\/*/

services:
  - docker
  - redis-server

install:
  - pip3 install -r docs/requirements/production.txt
  - make log
  - make settings

script:
  - make lint
  - make test
  - make check-deprecated
