
sudo: required  # Docker사용시 sudo권한 필요 https://docs.travis-ci.com/user/docker/

language: python
python:
  - "3.6"

branches:
only:
  - master
  - /^release\/*/
  - test/development

services:
  - docker
  - redis-server

install:
  - pip3 install -r docs/requirements/test.txt
  - make log
  - make settings
script:
  - make lint
  - make test
  - make check-deprecated


before_deploy:
  - pip install awscli


deploy:
  - provider: script
    script: bash docs/travis/deploy.sh
    env:
      ENV: development
      ACCOUNT_ECR: $DEV_ACCOUNT_ECR
      AWS_ACCESS_KEY_ID: $DEV_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $DEV_AWS_SECRET_ACCESS_KEY
    on:
      branch:
        - test/development
        - release/development
