
sudo: required

language: python
python:
  - "3.6"

branches:
only:
  - master
  - /^release\/*/

services:
  - docker
  - redis-server

stage:
 - test
 - deploy

jobs:
  include:
    - stage: test
      install:
        - pip3 install -r docs/requirements/test.txt
        - make log
        - make settings
      script:
        - make lint
        - make test
        - make check-deprecated
