
sudo: required  # Docker사용시 sudo권한 필요 https://docs.travis-ci.com/user/docker/

language: python
python:
  - "3.6"

branches:
only:
  - master
  - /^release\/*/

services:
  - docker
  - redis-server

install:
  - pip3 install -r docs/requirements/test.txt
  - make log
  - make settings
script:
  - make lint
  - make test
  - make check-deprecated


deploy:
  - provider: script
    script: sh docs/travis/deploy.sh
    on:
      branch:
        - release/development
        - release/production
