version: '3.4'

services:
  account-mariadb:
    image: mariadb:10.1
    container_name: account-mariadb
    restart: always
    volumes:
      - ./.tmp/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  account-www:
    image: ridibooks/python:bootstrap-django-2018.11.12.2
    container_name: account-www
    volumes:
      - .:/htdocs/www
    command: ['./docs/docker/wait_for_it.sh', 'mysqladmin ping -h account-mariadb -u root -proot', 'make docker-all']
    depends_on:
      - account-mariadb
    links:
      - account-mariadb

  account.local.ridi.io: # 로컬이나 테스트 환경에서 self call 할 때, host 설정을 위해 domain으로 container 이름을 설정함.
    image: nginx:stable
    container_name: account.local.ridi.io
    restart: always
    volumes:
      - ./docs/dev/nginx:/etc/nginx/conf.d:ro
      - ./docs/dev/cert:/etc/nginx/cert/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - account-www
    links:
      - account-www
