version: '3.4'

services:
  account-mariadb:
    image: mariadb:10.1
    container_name: account-mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./.tmp/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  account-redis:
    image: redis:4.0.6
    container_name: account-redis
    restart: always
    ports:
      - 6379:6379

  account-www:
    image: ridibooks/python:bootstrap-django-2018.06.05
    container_name: account-www
    volumes:
      - .:/htdocs/www
    ports:
      - 7001:7001
    command: ['./docs/docker/wait_for_it.sh', 'mysqladmin ping -h account-mariadb -u root -proot', 'make run-www']
    depends_on:
      - account-redis
      - account-mariadb
    links:
      - account-redis
      - account-mariadb

  account-nginx:
    image: nginx:stable
    container_name: account-nginx
    restart: always
    volumes:
      - ./docs/dev/nginx:/etc/nginx/conf.d:ro
      - ./docs/dev/cert:/etc/nginx/cert/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - account-www
    links:
      - account-www
