# Generated by Django 2.0.2 on 2018-02-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_internal_service',
            field=models.BooleanField(default=True, verbose_name='내부 서비스 여부'),
        ),
        migrations.AddField(
            model_name='application',
            name='jwt_token_type',
            field=models.IntegerField(choices=[(0, 'HS256'), (1, 'RS256')], default=0, verbose_name='JWT 알고리즘'),
        ),
        migrations.AlterField(
            model_name='application',
            name='authorization_grant_type',
            field=models.CharField(choices=[('authorization-code', 'Authorization code')], default='authorization-code', help_text='Authorization code 만 지원한다.', max_length=32, verbose_name='Grant 종류'),
        ),
        migrations.AlterField(
            model_name='application',
            name='client_type',
            field=models.CharField(choices=[('confidential', 'Confidential')], default='confidential', help_text='Confidential 만 지원한다.', max_length=32, verbose_name='Client 종류'),
        ),
    ]
