# Generated by Django 2.0.2 on 2018-05-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oauth2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='jwt_alg',
            field=models.CharField(choices=[('HS256', 'HS256'), ('RS256', 'RS256')], default='HS256', max_length=6,
                                   verbose_name='JWT 알고리즘'),
        ),
    ]
