# Generated by Django 2.0.2 on 2018-02-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_app', '0002_auto_20180223_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_internal_service',
            field=models.BooleanField(default=False, verbose_name='내부 서비스 여부'),
        ),
        migrations.AlterField(
            model_name='application',
            name='jwt_token_type',
            field=models.IntegerField(choices=[(0, 'HS256'), (1, 'RS256')], default=1, verbose_name='JWT 알고리즘'),
        ),
    ]
