# Generated by Django 2.0.2 on 2018-05-04 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oauth2_app', '0003_auto_20180424_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, db_column='oauth2_user_id', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='oauth2_app_application', to='account_app.OAuth2User'),
        ),
    ]
