# Generated by Django 2.0.2 on 2018-02-23 21:31

from django.db import migrations, models

import apps.domains.oauth2.models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_app', '0003_auto_20180223_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='jwt_hs_256_secret',
            field=models.TextField(default=apps.domains.oauth2.models.jwt_hs_256_secret, verbose_name='JWT Secret'),
        ),
    ]
