# Generated by Django 2.0.2 on 2018-05-16 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.django.db.mysql


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_app', '0003_auto_20180504_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='source_refresh_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refreshed_access_token', to=settings.OAUTH2_PROVIDER_REFRESH_TOKEN_MODEL),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='revoked',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_in_house',
            field=lib.django.db.mysql.TinyBooleanField(default=False, verbose_name='내부 서비스 여부'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='refreshtoken',
            unique_together={('token', 'revoked')},
        ),
    ]
