# Generated by Django 2.0.2 on 2018-02-23 21:32

from django.db import migrations, models

import apps.domains.oauth2.models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_app', '0004_application_jwt_hs_256_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='jwt_hs_256_secret',
            field=models.CharField(default=apps.domains.oauth2.models.jwt_hs_256_secret, max_length=32, verbose_name='JWT Secret'),
        ),
    ]
