# Generated by Django 2.1.7 on 2019-04-11 10:28

import apps.domains.oauth2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_app', '0005_auto_20190408_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(default=apps.domains.oauth2.models._create_random_refresh_token, max_length=32, unique=True),
        ),
    ]
