# Generated by Django 2.0.2 on 2018-02-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_app', '0005_auto_20180223_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='jwt_token_type',
            field=models.CharField(choices=[('HS256', 'HS256'), ('RS256', 'RS256')], default='RS256', max_length=6, verbose_name='JWT 알고리즘'),
        ),
    ]
