# Generated by Django 2.0.2 on 2018-02-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_app', '0006_auto_20180223_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='jwt_token_type',
            new_name='jwt_alg',
        ),
    ]
