# Generated by Django 2.0.2 on 2018-02-23 21:38

import apps.domains.oauth2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_app', '0007_auto_20180223_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='jwt_hs_256_secret',
            field=models.CharField(default=apps.domains.oauth2.models.jwt_hs_256_secret, max_length=32, verbose_name='JWT HS256 Secret'),
        ),
    ]
