# Generated by Django 2.0.2 on 2018-02-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_app', '0008_auto_20180223_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='is_internal_service',
            new_name='is_in_house',
        ),
    ]
