# Generated by Django 2.0.2 on 2018-02-27 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('oauth2_app', '0009_auto_20180223_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='oauth2_app_accesstoken', to='account_app.User'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth2_app_grant',
                                    to='account_app.User'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='oauth2_app_refreshtoken', to='account_app.User'),
        ),
    ]
