# Generated by Django 2.0.2 on 2018-03-05 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_app', '0010_auto_20180227_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refreshtoken',
            name='access_token',
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 19, 29, 55, 939058), editable=False, verbose_name='만료일'),
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='scope',
            field=models.TextField(blank=True, editable=False, verbose_name='Scope'),
        ),
    ]
