# Generated by Django 2.0.2 on 2018-03-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_app', '0011_auto_20180305_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='expires',
            field=models.DateTimeField(editable=False, verbose_name='만료일'),
        ),
    ]
