# Generated by Django 2.0.2 on 2018-03-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_app', '0012_auto_20180305_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='created',
        ),
        migrations.RemoveField(
            model_name='accesstoken',
            name='last_modified',
        ),
    ]
