version: '2'

services:
  account:
    mem_limit: 1024m
    mem_reservation: 512m
    image: 588135293606.dkr.ecr.ap-northeast-2.amazonaws.com/production/account/www
    container_name: account-www
    command: /usr/local/bin/uwsgi --ini /etc/uwsgi/www.ini
    logging:
      driver: awslogs
      options:
        awslogs-group: account-ecs-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: www
  account-nginx:
    mem_limit: 128m
    mem_reservation: 64m
    image: 588135293606.dkr.ecr.ap-northeast-2.amazonaws.com/production/account/nginx
    container_name: account-nginx
    restart: always
    ports:
      - 80
    depends_on:
      - account
    links:
      - account
    logging:
      driver: awslogs
      options:
        awslogs-group: account-ecs-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: www-nginx
