version: '2'

services:
  account-pm-test:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        PM_API_KEY: ${PM_API_KEY}
    image: pm-test/account-pm-test:${TAG}

  account-www:
    build:
      context: ../../
      dockerfile: ./docs/postman/account-www/Dockerfile
    image: pm-test/account-www:${TAG}

  account-mariadb:
    build:
      context: ../../
      dockerfile: ./docs/postman/account-mariadb/Dockerfile
    image: pm-test/account-mariadb:${TAG}

  account-ngix:
    build:
      context: ../../
      dockerfile: ./docs/postman/account-nginx/Dockerfile
    image: pm-test/account-nginx:${TAG}

