# Generated by Django 2.1.7 on 2019-03-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('worker_type', models.IntegerField(choices=[(10, 'Store User Crawler')], unique=True, verbose_name='worker_type')),
                ('last_date', models.DateTimeField(verbose_name='last_date')),
            ],
            options={
                'db_table': 'worker_status',
            },
        ),
    ]
