version: '2'

services:
  scheduler:
    extends:
      file: common.yml
      service: celery-worker
    mem_limit: 128m
    mem_reservation: 64m
    environment:
    - ENABLE_BEAT=1
    logging:
      driver: awslogs
      options:
        awslogs-group: /library/ecs/celery/scheduler
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: scheduler
