# Generated by Django 2.0.1 on 2018-01-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUrlAccessHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('staff_id', models.IntegerField(db_index=True, verbose_name='Staff')),
                ('method', models.IntegerField(choices=[(0, 'get'), (1, 'post'), (2, 'put'), (3, 'delete')], db_index=True, verbose_name='method')),
                ('url', models.CharField(db_index=True, max_length=200, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Admin 접근 로그',
                'verbose_name_plural': 'Admin 접근 로그 리스트',
                'db_table': 'admin_url_access_history',
            },
        ),
    ]
