version: '2'

services:
  account-high-worker:
    mem_limit: 512m
    mem_reservation: 128m
    environment:
      - ENABLE_BEAT=false
      - CELERY_APP_NAME=sites.celery.celery
      - CELERY_QUEUE=high_priority
      - CELERY_BROKER_URL=redis://account-dev.ypfw5e.0001.apn2.cache.amazonaws.com:6379/1
      - CELERY_WORKER_COUNT=2
    image: 689221834431.dkr.ecr.ap-northeast-2.amazonaws.com/development/account/www
    container_name: account-log-worker
    logging:
      driver: awslogs
      options:
        awslogs-group: account-ecs-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: celery
    command: /htdocs/www/docs/docker/celery/startup.sh
