version: '2'

services:
  account-scheduler:
    mem_limit: 512m
    mem_reservation: 128m
    environment:
      - ENABLE_BEAT=1
      - CELERY_APP_NAME=sites.celery.celery
      - CELERY_QUEUE=low_priority
      - CELERY_BROKER_URL=redis://account-dev.ypfw5e.0001.apn2.cache.amazonaws.com:6379/1
      - CELERY_WORKER_COUNT=2
    image: 689221834431.dkr.ecr.ap-northeast-2.amazonaws.com/development/account/www
    container_name: account-scheduler
    command: /htdocs/www/docs/docker/celery/startup.sh
    logging:
      driver: awslogs
      options:
        awslogs-group: account-ecs-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: celery
  account:
    mem_limit: 512m
    mem_reservation: 128m
    image: 689221834431.dkr.ecr.ap-northeast-2.amazonaws.com/development/account/www
    container_name: account-admin
    command: /usr/local/bin/uwsgi --ini /etc/uwsgi/admin.ini
    logging:
      driver: awslogs
      options:
        awslogs-group: account-ecs-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: admin
  account-nginx:
    mem_limit: 128m
    mem_reservation: 64m
    image: 689221834431.dkr.ecr.ap-northeast-2.amazonaws.com/development/account/nginx
    container_name: account-nginx
    restart: always
    ports:
      - 80
    depends_on:
      - account
    links:
      - account
    logging:
      driver: awslogs
      options:
        awslogs-group: account-ecs-logs
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: admin-nginx
