---
- hosts: all
  remote_user: ubuntu
  become: true
  become_user: root
  become_method: sudo
  vars:
    gitlab_url: https://gitlab.ridi.io/
    token: "{{ token }}"
    description: gitlab-runner
    executor: docker
    docker_default_image: ridibooks/python:bootstrap-django-2017.02.01

  roles:
    - gitlab-runner
