---
- name: Add GitLab's official repository
  shell: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | bash
  become: yes
  become_user: root
  become_method: sudo

- name: install GitLab Runner
  apt: name=gitlab-runner

- name: register GitLab Runner
  command: gitlab-runner register >
    --non-interactive
    --url '{{ gitlab_url }}'
    --registration-token '{{ token }}'
    --description '{{ description }}'
    --tag-list ''
    --executor '{{ executor }}'
    --docker-image '{{ docker_default_image }}'
